# Generated by Django 5.2.17 on 2026-08-29 13:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("korean_title", models.CharField(max_length=240)),
                ("original_title", models.CharField(max_length=240)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("draft", "초안"), ("active", "활성"), ("retired", "종료")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("display_label", models.CharField(max_length=100)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("draft", "초안"), ("active", "활성"), ("retired", "종료")],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AggregateKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "completion_scope",
                    models.CharField(
                        choices=[
                            ("main_story", "메인 스토리"),
                            ("main_plus_optional", "메인 + 선택"),
                            ("completionist", "완전 공략"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aggregate_keys",
                        to="catalog.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aggregate_keys",
                        to="catalog.platform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaytimeAggregateRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("rule_revision", models.CharField(default="median-v1", max_length=32)),
                ("median_minutes", models.PositiveIntegerField()),
                ("sample_count", models.PositiveIntegerField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("current", "현재"),
                            ("superseded", "대체됨"),
                            ("retired", "종료"),
                        ],
                        default="current",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="catalog.aggregatekey",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="catalog.playtimeaggregaterevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_uuid", models.UUIDField(unique=True)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.UUIDField()),
                ("action", models.CharField(max_length=64)),
                ("contract_revision", models.CharField(default="ops/v1", max_length=32)),
                ("rule_revision", models.CharField(blank=True, max_length=32)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("succeeded", "성공"), ("rejected", "거절")], max_length=16
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "aggregate_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.playtimeaggregaterevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AggregateObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "aggregate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.playtimeaggregaterevision",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="aggregatekey",
            name="current_revision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_key",
                to="catalog.playtimeaggregaterevision",
            ),
        ),
        migrations.CreateModel(
            name="PlaytimeObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_uuid", models.UUIDField(unique=True)),
                (
                    "payload_fingerprint",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "completion_scope",
                    models.CharField(
                        choices=[
                            ("main_story", "메인 스토리"),
                            ("main_plus_optional", "메인 + 선택"),
                            ("completionist", "완전 공략"),
                        ],
                        max_length=32,
                    ),
                ),
                ("minutes", models.PositiveIntegerField()),
                ("provenance_identity", models.CharField(max_length=240)),
                ("observation_date", models.DateField()),
                (
                    "moderation_state",
                    models.CharField(
                        choices=[("draft", "초안"), ("approved", "승인"), ("rejected", "거절")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playtime_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="catalog.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="catalog.platform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playtimeaggregaterevision",
            name="included_observations",
            field=models.ManyToManyField(
                related_name="aggregate_revisions",
                through="catalog.AggregateObservation",
                to="catalog.playtimeobservation",
            ),
        ),
        migrations.CreateModel(
            name="ModerationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("draft", "초안"), ("approved", "승인"), ("rejected", "거절")],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("operation_uuid", models.UUIDField(unique=True)),
                ("input_hash", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_decision",
                        to="catalog.playtimeobservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aggregateobservation",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.playtimeobservation"
            ),
        ),
        migrations.CreateModel(
            name="GameAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=20)),
                ("text", models.CharField(max_length=240)),
                ("normalized_text", models.CharField(editable=False, max_length=240)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("korean", "한국어"),
                            ("original", "원어"),
                            ("english", "영어"),
                            ("alternate", "대체명"),
                            ("edition", "에디션"),
                        ],
                        max_length=16,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="catalog.game",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "normalized_text"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "locale", "normalized_text"),
                        name="unique_normalized_alias_per_game_locale",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aggregatekey",
            constraint=models.UniqueConstraint(
                fields=("game", "platform", "completion_scope"), name="unique_aggregate_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="playtimeobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes__gt", 0)), name="observation_minutes_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="playtimeaggregaterevision",
            constraint=models.UniqueConstraint(
                fields=("aggregate_key", "revision_number"), name="unique_aggregate_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="playtimeaggregaterevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "current")),
                fields=("aggregate_key",),
                name="one_current_revision_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="playtimeaggregaterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("sample_count__gte", 3)), name="aggregate_minimum_sample"
            ),
        ),
        migrations.AddConstraint(
            model_name="playtimeaggregaterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("median_minutes__gt", 0)), name="aggregate_median_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="aggregateobservation",
            constraint=models.UniqueConstraint(
                fields=("aggregate_revision", "observation"), name="unique_observation_per_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="aggregateobservation",
            constraint=models.UniqueConstraint(
                fields=("aggregate_revision", "position"),
                name="unique_observation_position_per_revision",
            ),
        ),
    ]
